version: "3.8"

services:
  sms-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sms-api
    restart: always
    expose:
      - "9000"    # Internal PHP-FPM port (not published directly)
    volumes:
      - ./:/var/www
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # These environment variables are used by the nginx-proxy and letsencrypt companion
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    depends_on:
      - sms-db
    networks:
      - sms-network

  sms-db:
    image: postgres:13-alpine
    container_name: sms-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - sms-network

networks:
  sms-network:
    external: true
